export const metadata = {
  title: 'About',
  description: 'Generated by create next app',
}

export default function Home() {
  return (
    <div className="h-full flex items-center justify-center bg-gray-100 py-14">
      <div className="bg-white rounded-lg shadow-lg p-8 w-96">
        <h2 className="text-slate-800 text-4xl font-semibold mb-6">About Us</h2>
        <p className="text-slate-600 text-lg mb-4">
          We are a team of passionate individuals dedicated to providing high-quality products and services.
        </p>
        <p className="text-lg text-slate-600">
          Our mission is to create innovative solutions that make a positive impact on people's lives.
        </p>
      </div>
    </div>
  )
}
